### ISSUE TITLE
点选开关按钮无效

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [Mara-Li/obsidian-regex-mark#1]
<img width="786" alt="image" src="https://github.com/Mara-Li/obsidian-regex-mark/assets/71814666/a12336b0-69e2-4dd4-8f68-b852ebf30e5c">

**Comment by shoudeyunkaijianyueming** [comment]
<img width="47" alt="image" src="https://github.com/Mara-Li/obsidian-regex-mark/assets/71814666/b8c4cd3d-49e3-4278-94e7-3f9ca6b584ef">
点击不了，没反应

**Comment by Mara-Li** [comment]
Issue not in english will be autoclosed.

**Comment by ms3056** [comment]
Some of the toggles can't be clicked. I don't need them myself, but I came here to thank you for making this awesome plugin - well done.

**Comment by Mara-Li** [comment]
Yeah, it's normal!
I updated the plugin to indicate why they can't be enabled.
It must follow some condition, aka the existance of a regex groups like `(.*)` for example. I set a link in the settings to help.
