### ISSUE TITLE
[FR]: Import & Export Regex Rules

### ISSUE THREAD

**Issue by Moyf** [Mara-Li/obsidian-regex-mark#10]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### What solution do you want to see ?

Hi, since the `css` files are easy to translate, could you provide a function to export and import the regex rules? This would allow us to share the rules and CSS more conveniently.
![image](https://github.com/user-attachments/assets/e1d842e4-1b10-478b-bb9d-a58a6bbdca47)

While I believe that the `data.json` of the Plugin could also achieve this, manipulating it might be too complex for most users.

### Obsidian information

```bash session
v1.6.7
```

### Plugin version

1.7.2

**Comment by Mara-Li** [comment]
Oh, yeah. Can be useful!
I already coded this for another plugin so it won't be difficult to port it.

**Comment by Moyf** [comment]
> Oh, yeah. Can be useful! I already coded this for another plugin so it won't be difficult to port it.

Sounds great!  🥳

**Comment by Mara-Li** [comment]
Oh yeah, good idea.
