### ISSUE TITLE
[FR]: make regex case sensitive by default

### ISSUE THREAD

**Issue by dsmf** [Mara-Li/obsidian-regex-mark#12]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### What solution do you want to see ?

a regex can be made case sensitive but if the case-insensitivity is defined inside the plugin one cannot force case sensitivity

### OS

Windows

### Obsidian information

```bash session
not relevant
```

### Plugin version

1.7.2

**Comment by Mara-Li** [comment]
Will add a flags option
