### ISSUE TITLE
[Bug]: Should not apply to code listings

### ISSUE THREAD

**Issue by dsmf** [Mara-Li/obsidian-regex-mark#13]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

The regex is also applied to code listings. This makes the plugin useless for me. 

### How to reproduce ?

use any word that is matched by a defined regex inside a code listing

### OS

Windows

### Obsidian information

```bash session
not relevant
```

### Plugin version

1.7.2

**Comment by Mara-Li** [comment]
What do you mean by "code listing" ?
