### ISSUE TITLE
[FR]: Use {{ and }} as start and end

### ISSUE THREAD

**Issue by writeblankspace** [Mara-Li/obsidian-regex-mark#14]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

I wanted to style my clozes for my flashcards plugin. Each "cloze" is marked with curly braces: `hello {{I am a cloze}}`

however, I can't put `{{` nor `}}` as the start and end because I can't us `\`.

### What solution do you want to see ?

Allow the use of `\` for the start and end?

### Describe the alternative you've considered

Just select the `{{` and not the content

### OS

Linux

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 14:02:12 +0000 6.6.45-1-lts
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 7
		1: Style Settings v1.0.9
		2: Calendar v1.5.10
		3: Tasks v7.9.0
		4: Templater v2.4.2
		5: Markdown table checkboxes v2.0.8
		6: Spaced Repetition v1.12.5
		7: Regex Mark v1.8.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Plugin version

1.8.0

**Comment by Mara-Li** [comment]
Maybe I could allow to change the pattern for open/close trigger !
