### ISSUE TITLE
[FR]: Hide the characters used for the opening and closing tags

### ISSUE THREAD

**Issue by dmantisk** [Mara-Li/obsidian-regex-mark#16]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

I'm using this plugin to make stuff inside double curly brackets (`{{` and `}}`) be highlighted in an alternate colour. The specific characters were chosen for use with Spaced repetition plugin's cloze feature.

![image](https://github.com/user-attachments/assets/6256f619-7271-4c50-82ed-b8d0b5daf563)

However, I'd like to hide the brackets from being visible

### What solution do you want to see ?

Have the tag be hidden by default, or have an option to do so.

### Describe the alternative you've considered

Using css to hide; I'm couln't find anything on it, as supposedly you can't hide characters unless they are specific like a `#tag` or a heading.

### Anything else?

{
  "mark": [
    {
      "regex": "[open:\\{\\{](.*)[close:\\}\\}]",
      "class": "highlight2",
      "hide": true,
      "viewMode": {
        "reading": true,
        "source": false,
        "live": true,
        "codeBlock": false
      }
    }
  ],
  "pattern": {
    "open": "\\[open:(.*?)\\]",
    "close": "\\[close:(.*?)\\]"
  }
}

### OS

Windows

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.5
	Installer version: v1.7.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 14
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 16
		1: Style Settings v1.0.9
		2: Minimal Theme Settings v8.1.1
		3: Note Toolbar v1.14.9
		4: Ribbon Divider v1.1.1
		5: Note Definitions v0.26.1
		6: Custom Attachment Location v4.27.5
		7: Templater v2.9.1
		8: Settings Search v1.3.10
		9: Badges v1.1.0
		10: Excalidraw v2.6.7
		11: Iconize v2.14.4
		12: Modal forms v1.52.0
		13: PopKit v1.0.13
		14: Sheets Extended v1.2.10
		15: Spaced Repetition v1.13.2
		16: Regex Mark v1.9.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Plugin version

1.9.2

**Comment by Mara-Li** [comment]
Please read the documentation. You can already do that… See #14

**Comment by dmantisk** [comment]
> Please read the documentation. You can already do that… See #14

Apologies, but this request was about _hiding_ the tags. I'm now thinking it should have been a bug report.

The tags are not hidden despite the toggle being on
![image](https://github.com/user-attachments/assets/8c0f2e9c-f09c-43d5-8edc-999612ccff81)
![image](https://github.com/user-attachments/assets/b2da57b2-4e41-4eec-a91e-7c1b1c00ffd5)

**Comment by Mara-Li** [comment]
OK. It's a total difference problem then.
Will investigate.
