### ISSUE TITLE
[FR]: regex that can match newline can be supported？

### ISSUE THREAD

**Issue by calmwaves111** [Mara-Li/obsidian-regex-mark#4]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### What solution do you want to see ?

Hello, I noticed: regex that can match newline was **excluded** in 1.6.3
Can we find a way to support this situation.
I know, the line break in reading mode is`<br>`
Implementing this may be very difficult

### Obsidian information

```bash session
win10,ob1.6.3
(Oh, I found a very coincidental thing, both this plugin and OB is 1.6.3)
```

### Plugin version

1.6.3

**Comment by Mara-Li** [comment]
No.
It will crash obsidian if matching new line.

**Comment by calmwaves111** [comment]
thanks for your reply
This plugin is great right now
