### ISSUE TITLE
[FR]: I want to be able to support the display in reading mode

### ISSUE THREAD

**Issue by jiajiala** [Mara-Li/obsidian-regex-mark#7]
I want to be able to support the display in reading mode

![image](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/8d3665a6-81de-49fc-96a1-11ec3aa1e701)
This is my css, but this only works in edit mode
But I don't know how to make it work in reading mode

**Comment by Mara-Li** [comment]
Any class should works in reading mode, unless you disable it.
I need more information about the class and regex to understand why it doesn't work.

**Comment by jiajiala** [comment]
> Any class should works in reading mode, unless you disable it. I need more information about the class and regex to understand why it doesn't work. 
https://github.com/Mara-Li/obsidian-regex-mark/issues/8
