### ISSUE TITLE
[Bug]: In table mode, the display is different from that in normal cases

### ISSUE THREAD

**Issue by jiajiala** [Mara-Li/obsidian-regex-mark#8]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

![image](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/c9dea944-0929-4d63-b71a-3dfdccd83a7d)
![image](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/e16a5d1b-1283-4c7c-a0c8-0f2af5b323fc)
As shown in the figure, xx does not change color in the table, but is correct under normal conditions

### Minimal Reproducible Example

 {
    "regex": "“(.*?)”",
    "class": "ccsse",
    "hide": false
  },

.ccsse{
    background-color: rgb(103 33 0);
  }
  
  

### Obsidian information

```bash session
·
```

### Plugin version

1.7.0

**Comment by Mara-Li** [comment]
Can i have the markdown for testing ? 
Are you in reading or live preview mode ?

**Comment by jiajiala** [comment]
> Can i have the markdown for testing ？ Are you in reading or live preview mode ? 

[Test12.md](https://github.com/user-attachments/files/15985772/Test12.md)
![4](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/cb29c553-6efd-4b47-9917-3234599155cd)

In either mode, it is not possible to represent "xx" as all yellow

**Comment by Mara-Li** [comment]
I forgot to add support for `th` in the markdown processor, and also forgot to set the regex on `g` (global).
Now fixed for table
