### ISSUE TITLE
[Bug]: When any text is discolored, it will destroy the entire color change

### ISSUE THREAD

**Issue by jiajiala** [Mara-Li/obsidian-regex-mark#9]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

![4](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/97c7fb1f-97ad-4702-b74f-175121301547)
The above is normal, and the following words are highlighted by two words, and the whole change of color doesn't work

Hopefully, when the default format makes it red, I can still make special marks on specific words
![image](https://github.com/Mara-Li/obsidian-regex-mark/assets/73203026/fbc0890b-351f-444b-ab30-bdb3a6ab124a)

### Minimal Reproducible Example

“aaa<mark class="hltr-兰">aa</mark>aa”

### Configuration

```JSON
·
```

### Obsidian information

```bash session
·
```

### Plugin version

1.7.1

**Comment by Mara-Li** [comment]
I dont think it's even possible to do it using my methods to add style :/.
